name: GitHub-Profile-3D-Contrib

on:
  schedule: # 10:00 BRT == 13:00 UTC
    - cron: "0 13 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v3
      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
          USERNAME: PedroHda
      - name: Commit & Push
        run: |
          git config user.name PedroHda
          git config user.email pedrohda.ph@gmail.com
          git add -A .
          git commit -m "generated"
          git push
